### ISSUE TITLE
couldn't deploy it, is there any guide to do so?

### ISSUE THREAD

**Issue by cayaner** [vuetifyjs/webpack-ssr#14]

**Comment by johnleider** [comment]
Currently not, something that I need to get to.

**Comment by cayaner** [comment]
thanks, it was solved, you already answered me: https://zeit.co/now#get-started
i was wondering about the Vue 2.3.0 modifications if it will be implemented here soon?
thanks in  advance ...

**Comment by johnleider** [comment]
Yes, but no ETA. I'm still reviewing them, and the update to them will be the final major update for this template as I will be focusing on the NUXT template moving forward.

**Comment by cayaner** [comment]
Great, i really appropriate your efforts .. :zap:
personally i like your way of getting it done .. :fire:
