### ISSUE TITLE
Project information is not used in package.json

### ISSUE THREAD

**Issue by dsbert** [vuetifyjs/webpack-ssr#2]
When running `vue init vuetifyjs/webpack-ssr`, The CLI asks for a name, description, and author. However, `package.json` is created with the default values.

```json
  "name": "vuetify-webpack-ssr",
  "description": "A Vue.js project",
  "author": "John Leider <john.j.leider@gmail.com>",
```

**Comment by johnleider** [comment]
I'll get this updated, ty.
