### ISSUE TITLE
Unknown custom element: VCard, VDialog, VTooltip

### ISSUE THREAD

**Issue by tforssander** [vuetifyjs/webpack-ssr#31]
Hi again, 

when using a-la-carte components option, there are some missing components (VCard, VDialog, VTooltip), specified in the `./assets/app.js` file, which is causing the `[Vue warn]: Unknown custom element: <v-xxx>` error since they are used in `App.vue` and `WelcomeView.vue`.

Thanks!

**Comment by nekosaur** [comment]
Fixed in 32020ed388d0a75112ffcf478938aef4ed0b5f5f. However as far as I could tell only VCard was missing.

**Comment by tforssander** [comment]
@nekosaur Ah, you're right, thanks you!
