### ISSUE TITLE
/dist/** files doesn't have hashes in filename - cache problem

### ISSUE THREAD

**Issue by SystemZ** [vuetifyjs/webpack-ssr#9]
Hi, I'm not expert on webpack but I see files that change constantly without name change which causes trouble for deployment with heavy caching.

Current filenames:
app.js
vendor.js 
manifest.js

Screencap from `npm run dev` but for `npm run build` is identical.

![screenshot from 2017-02-08 03-20-23](https://cloud.githubusercontent.com/assets/1836094/22720840/ac1af9ca-edad-11e6-83f3-39c01b368f05.png)

How can I fix it in webpack config?

Expected filename styles:
app.Y5ZjZjT5Fd.js
vendor.YC3mzY.js 
manifest.2fcr4jY.js

**Comment by johnleider** [comment]
Does this relate to your issue? https://github.com/vuetifyjs/vuetify/issues/40

**Comment by SystemZ** [comment]
Sorry for trouble, it was my fault. Work at night is problematic.

`server.js` didn't see my env staging as production, but as dev, so it was serving wrongly.

For people with similar problem, when you are using more than dev and prod envs, make sure these lines are ok:
https://github.com/lvlup-pro/spawn-frontend-material/blob/d4e91a517890d83c8e82a2d63ad169ab09d0207b/server.js#L2

https://github.com/lvlup-pro/spawn-frontend-material/blob/d4e91a517890d83c8e82a2d63ad169ab09d0207b/server.js#L17
